name: chooseNext

on:
  schedule:
    # UTC のため日本時間 +9
    - cron: '00 2 * * 1'
env:
  NOTION_KEY: ${{ secrets.NOTION_KEY }}
  NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

jobs:
  chooseNext:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/node-setup
    - run: yarn start:chooseNext
